from datetime import datetime
from database import opportunities_collection
from CRUD import Opportunity

opportunities_data = [
    {
        "title": "AI-Driven Traffic Management System",
        "type": "Project",
        "organization": "Dr. Sarah Smith (CS Dept)",
        "description": "Developing a reinforcement learning model to optimize traffic signal timings in real-time using camera feeds.",
        "skills": ["Python", "PyTorch", "Computer Vision"],
        "posted_date": datetime(2025, 11, 20),
        "deadline": "2025-12-15",
    },
    {
        "title": "Frontend Developer Intern",
        "type": "Internship",
        "organization": "TechFlow Solutions",
        "description": "Work on our core product dashboard using React and Next.js. Experience with modern UI libraries is a plus.",
        "skills": ["React", "Next.js", "TypeScript", "CSS"],
        "posted_date": datetime(2025, 11, 25),
        "deadline": "2025-12-10",
    },
    {
        "title": "Blockchain for Supply Chain",
        "type": "Project",
        "organization": "Prof. Alan Turing (IT Dept)",
        "description": "Research and implementation of a decentralized ledger for tracking pharmaceutical supply chains.",
        "skills": ["Solidity", "Ethereum", "Web3.js"],
        "posted_date": datetime(2025, 11, 18),
        "deadline": "2025-12-20",
    },
    {
        "title": "Data Science Intern",
        "type": "Internship",
        "organization": "DataMinds Corp",
        "description": "Analyze large datasets to identify market trends. Proficiency in SQL and Pandas required.",
        "skills": ["Python", "SQL", "Pandas", 'Tableau'],
        "posted_date": datetime(2025, 11, 22),
        "deadline": "2025-12-05",
    },
    {
        "title": "Smart Home Automation IoT",
        "type": "Project",
        "organization": "Dr. John Doe (EE Dept)",
        "description": "Building a prototype for a secure, low-power IoT network for smart home devices.",
        "skills": ["C++", "IoT", "Embedded Systems", "Network Security"],
        "posted_date": datetime(2025, 11, 26),
        "deadline": "2025-12-30",
    },
]

def seed():
    print("Seeding opportunities...")
    # Optional: Clear existing data
    # opportunities_collection.delete_many({})
    
    for opp_data in opportunities_data:
        # Check if opportunity already exists to prevent duplicates
        if not opportunities_collection.find_one({"title": opp_data["title"]}):
            opp = Opportunity(**opp_data)
            # Use exclude={'id'} because _id is generated by Mongo
            opportunities_collection.insert_one(opp.dict(exclude={'id'}, by_alias=True))
            print(f"Inserted: {opp.title}")
        else:
            print(f"Skipped (Exists): {opp_data['title']}")
            
    print("Seeding complete!")

if __name__ == "__main__":
    seed()
